export * from './addreess-input.dto';
export * from './aggressor-input.dto';
export * from './contact-input.dto';
export * from './document-input.dto';
export * from './input.dto';
export * from './main-form-input-input.dto';
export * from './person-input.dto';
export * from './questions-input.dto';
export * from './victim-input.dto';
